### ISSUE TITLE
There is a way to have physical feedback when touching?

### ISSUE THREAD

**Issue by witalobenicio** [react-native-community/react-native-platform-touchable#6]
For example a sound or vibration?

**Comment by Cnordbo** [comment]
Im guessing not be default? Unless the platform does it by itself with settings. ( i noticed android makes this droplet sound on the emulator atleast, everytime i touch something). 
But you could always add Vibration https://facebook.github.io/react-native/docs/vibration to the onPress function if wanted. Or https://github.com/zmxv/react-native-sound if sound is wanted :)

**Comment by brentvatne** [comment]
you could use [expo-haptics](https://docs.expo.io/versions/v32.0.0/sdk/haptics/) along with `onPressIn` and `onPress` - here's an example: https://snack.expo.io/@notbrent/haptic-impact
